# Nav
social:
  Github: https://github.com/jeremylv1992

# Background image, color
background: 'url(http://osly086qe.bkt.clouddn.com/button-bg.png) #f3f3f3'

# Favicon
favicon: http://osly086qe.bkt.clouddn.com/favicon.ico

# SEO
keywords: 'hexo, autumn'

# Widgets, enable at least one
widgets:
  archive: enabled
  tag: enabled
